import { gql, useQuery } from '@apollo/client';
import Head from 'next/head'
import Image from 'next/image'
import { useState } from "react";
import styles from '../styles/Home.module.css'
import { useAuth } from "../lib/auth";

const SignIn = () => {
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const { signIn } = useAuth()

  function onSubmit(e) {
    e.preventDefault()
    signIn({ username, password })
  }

  return (
    <div>
      <form onSubmit={onSubmit}>
        <input type="text" placeholder="username" onChange={(e) => setUsername(e.target.value)}></input>
        <input type="password" placeholder="password" onChange={(e) => setPassword(e.target.value)}></input>
        <button type="submit">Log In</button>
      </form>
    </div>
  )
}

const EpisodeFeed = () => {
  const FeedQuery = gql`
    {
      episodeFeed(first: 50) {
        id
        title
        audio
        podcast {
          title
        }
      }
    }
  `

  const { data } = useQuery(FeedQuery)
  const { signOut } = useAuth()

  return (
    <div>
      <h1>Episode Feed:</h1>
      <ul>
        {data?.episodeFeed.map( (e) => {
          return <li key={e.title}>{e.title}</li>
        })}
      </ul>
      <button onClick={() => signOut()}>Sign Out</button>
    </div>
  )
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>KD.FM</h1>
        <SignIn />
        <EpisodeFeed />
      </main>

    </div>
  )
}
